- src: git@github.com:Casecommons/aws-cloudformation.git
  scm: git
  version: 0.4.0
  name: aws-cloudformation
- src: git@github.com:Casecommons/aws-sts.git
  scm: git
  version: 0.1.2
  name: aws-sts
- src: git@github.com:Casecommons/aws-ecs-tasks.git
  scm: git
  version: 0.1.0
  name: aws-ecs-tasks