cf_stack_name: "{{ 'intake-api-' + env }}"
cf_stack_tags:
  org:business:owner: CA Intake
  org:business:product: Intake API
  org:business:severity: High
  org:tech:environment: "{{ env }}"
  org:tech:contact: pema@casecommons.org

cf_stack_inputs:
  ApplicationAutoscalingDesiredCount: "{{ config_application_desired_count }}"
  ApplicationAMI: "{{ config_application_ami }}"
  ApplicationInstanceType: "{{ config_application_instance_type }}"
  ApplicationLoadBalancerPort: "{{ config_application_frontend_port }}"
  ApplicationPort: "{{ config_application_port }}"
  ApplicationKeyName: "{{ config_application_keyname }}"
  ApplicationDockerImage: "{{ config_application_image }}"
  ApplicationDockerImageTag: "{{ config_application_tag }}"
  ElasticsearchAutoscalingDesiredCount: "{{ config_es_desired_count }}"
  ElasticsearchAMI: "{{ config_es_ami }}"
  ElasticsearchInstanceType: "{{ config_es_instance_type }}"
  ElasticsearchLoadBalancerPort: "{{ config_es_frontend_port }}"
  ElasticsearchPort: "{{ config_es_port }}"
  ElasticsearchKeyName: "{{ config_es_keyname }}"
  ElasticsearchDockerImage: "{{ config_es_image }}"
  ElasticsearchDockerImageTag: "{{ config_es_tag }}"
  Environment: "{{ env }}"
  LogRetention: "{{ config_log_retention }}"
  NginxDockerImage: "{{ config_nginx_image }}"
  NginxDockerImageTag: "{{ config_nginx_tag }}"
  DbStorage: "{{ config_db_storage }}"
  DbInstanceType: "{{ config_db_instance_type }}"
  DbName: "{{ config_db_name }}"
  DbUsername: "{{ config_db_username }}"
  DbPassword: "{{ config_db_password }}"
  SecretKeyBaseCipher: "{{ config_application_secret_key_base }}"